version: '3'

services:
  redis:
    image: redis
    container_name: redis
    ports:
      - '6380:6379'

  db:
    image: postgres
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - core/env/local/.env

  web:
    build: .
    container_name: web
    command: gunicorn -w 4 -b 0.0.0.0:5000 app:app
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - core/env/local/.env

  celery:
    build: .
    container_name: celery
    command: celery -A app.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - core/env/local/.env

  flower:
      build: .
      container_name: flower
      command: celery flower
      ports:
        - '5555:5555'
      depends_on:
        - redis
        - db
        - celery
      env_file:
        - core/env/local/.env

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A app.celery beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
      - celery
    env_file:
      - core/env/local/.env
